exec_worker=20
mock_worker=1
epoch=500000

[user]
id:int   = {incr:100:1}
name     = {rand:case:5:10}Mocked
age:int  = {rand:range:18:50}
phone    = {rand:dict:182,139,180,137,136}{rand:num:9}
email    = {rand:lcase,num:1:3}{rand:case,num:4}@{rand:dict:gmail,qq,163,126}.{rand:dict:com,cn}
password = {rand:ucase,num:16}

[user_detail]
text = {input:prefix}hello{input:prefix}
user_id:int = {var:user.id}
